### ISSUE TITLE
E-Hentai Plugin

### ISSUE THREAD

**Issue by twiddli** [happypandax/plugins#1]
- [x] fetch metadata
- [x] download galleries

**Comment by tallos** [comment]
With the death of sadpanda this plugin no longer seems to be capable of fetching tags/metadata from any galleries that where fjorded. Is there a way to allow it to fetch metadata/tags for these "lost" galleries similar to dnsev-h's Gallery Resurrect which still appears to work?

**Comment by twiddli** [comment]
fully implemented by `v0.12.0`
