### ISSUE TITLE
EHentai Metadata - Temp Ban from e-hentai.org

### ISSUE THREAD

**Issue by Pakloust** [happypandax/plugins#10]
The plugin needs a delay mechanic implemented. As it is now e-hentai.org is banning due to too much bandwidth use/no delay.

"Your IP address has been temporarily banned for excessive pageloads which indicates that you are using automated mirroring/harvesting software. "

**Comment by twiddli** [comment]
Hi, I have increased the default delay value on EH requests. You can tweak this value yourself in the `network.delays` setting inside your `config.yaml`.
