### ISSUE TITLE
File Metadata plugin not detecting "parody:" category

### ISSUE THREAD

**Issue by waz1500** [happypandax/plugins#12]
File Metadata 0.2.0b installed
happypandax0.5.2.win

When importing my manga into HPX the "Parody:" entry does not automatically fill in even when the data is there in the info.txt file using the File Metadata plugin. 

I use hdoujin downloader to grab my manga and create the appropriate info.txt v2 metadata file titled info.txt. An example of the affected manga is attached. [info.txt](https://github.com/happypandax/plugins/files/2553571/info.txt)

I have also noticed that the "Circle:" entry is missing when clicking edit on an existing imported gallery. So I can't add or edit an existing circle if it was found by the plugin. Is this by design?

**Comment by twiddli** [comment]
Hi, you're right, it doesn't seem like `PARODY` is getting picked up. I'll add this along with #6 soonish enough.
>I have also noticed that the "Circle:" entry is missing when clicking edit on an existing imported gallery

Yes, this might be a bit confusing, but a circle is bound to an artist and not a gallery. To edit a circle, click on an artist and a row for circles will appear in the popup.

**Comment by twiddli** [comment]
Implemented in `0.3.0b`
