### ISSUE TITLE
EHentai Metadata plugin failing to initialize

### ISSUE THREAD

**Issue by TheJoe49** [happypandax/plugins#23]
**Describe the bug**
The EHentai Metadata plugin failed to initialize 

**To Reproduce**
Not sure

**Plugin Logs**
Jun-06 23:41:04--INFO   pluginctx.ehentai-metadata: Installing plugin
Jun-06 23:41:04--INFO   pluginctx.ehentai-metadata: Marking plugin for initialization
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Initiating plugin
Jun-06 23:41:06--ERROR  pluginctx.ehentai-metadata: An unhandled exception 'SyntaxError' was raised during plugin initialization
Traceback (most recent call last):
  File "happypanda\core\plugins.py", line 789, in init
  File "<string>", line 3, in <module>
  File "C:\Users\Gudrith\Documents\HappyPanda X\data\plugins\1572a650-5352-4d62-802f-8dfb983f9231.hpxplugin\main.py", line 470
    gcircles.append(CircleData(name=ca  pitalize_text(circlename)))
                                                    ^
SyntaxError: invalid syntax
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Unloading plugin
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Disabling plugin: Failed to initialise plugin
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Marking plugin for initialization
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Plugin failed
Jun-06 23:41:06--INFO   pluginctx.ehentai-metadata: Marking plugin for initialization

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/16162727/59404385-f3a1e000-8d6b-11e9-96f2-dabf57d9cce3.png)

**Environment:**
 - OS: Windows 10
 - Chrome
 - HPX Version 0.10

**Comment by twiddli** [comment]
This should now be fixed. If you update through a client and and get a Failed to initialise error, just restart hpx and it should work again.
