### ISSUE TITLE
Update E-Hentai plugins

### ISSUE THREAD

**Issue by CirnoT** [happypandax/plugins#28]
E-Hentai plugins need updating.

---

- E-Hentai Login one needs exhentai to be removed.
- E-Hentai Metadata needs to be updated to remove exhentai as well as to always send cookies/session which will allow certain users to still search for forbidden content on E-Hentai frontend.
- E-Hentai Metadata needs to be updated for new site design.

---

See https://github.com/CirnoT/happypandax-plugins/blob/master/plugins/EHentai%20Metadata/main.py as well as https://github.com/CirnoT/happypandax-plugins/blob/master/plugins/EHentai%20Login/main.py for example of how such updates could be done. Do note however that E-Hentai Metadata one was updated only for thumbnails view as this is what I use.

**Comment by twiddli** [comment]
Hello, wouldn't you like to make a pull request with your changes?

**Comment by CirnoT** [comment]
The changes are incomplete as it is now.

**Comment by twiddli** [comment]
So you're not interested in completing it?

**Comment by CirnoT** [comment]
At some point maybe, but I don't have time currently to add support for other views to E-Hentai Metadata plugin and since I'm using thumbnail view personally that's all I need.

**Comment by twiddli** [comment]
I'm guessing this is irrelevant now?
