### ISSUE TITLE
EH Login needs more complete cookies

### ISSUE THREAD

**Issue by notlixiang** [happypandax/plugins#36]
The current EHentai Login plugin only collects ipb_member_id and ipb_pass_hash as credentials. This leads to login failure usually on my device and this problem can be solved by adding igneous and sk to the cookie. I tried this out by modifying the python script. Please collect igneous information for ExHentai login.

**Comment by TindalosHound** [comment]
Since there is no sign that this is about to get fixed, would you mind sharing how you got it working? I haven't been able to use this plugin for many months now. Every time I try to log in with it, I get "No user credentials provided".
