### ISSUE TITLE
Unable to download nhentai galleries

### ISSUE THREAD

**Issue by jdevoldere** [happypandax/plugins#43]
Describe the issue
"No matching download handler found for url https://nhentai.net/g/..." whenever I try to add an url for download.

To Reproduce

    Clean install of HPX
    Create an admin user
    Start server
    Open Webclient and login
    Go to Downloads
    Add a random nhentai gallery url
    See error in log window (No matching download handler found for url https://nhentai.net/g/...)

Expected behavior
The hentai gallery to be downloaded without errors.

Environment:

    OS: Windows 10
    Browser and browser version: Firefox latest
    HPX Version: v0.13.3

Additional context
Tested on two separate machines and same issue. The same issue also occurs with e-hentai galleries.

**Comment by twiddli** [comment]
> No matching download handler found for url https://nhentai.net/g/...

This error means that you haven't enabled the nhentai downloader plugin
