### ISSUE TITLE
Character Tags for HDoujinDownloader Galleries

### ISSUE THREAD

**Issue by observeroftime02** [happypandax/plugins#6]
Can we include the "CHARACTERS" tag created in the info.txt file as a tag?

Currently, the information about the Characters exist in the info.txt file, but are not being included as a tag, due to not being part of the "TAGS" field, but the separate "CHARACTERS" field. I'm sure this can be arranged somehow. My understanding of python is extremely limited, so the modification required to make this work is beyond my skill. 

I've got some 4000 touhou doujins in the Database, but after import i realized i can not search by character. I'm thinking that by simply adding the "CHARACTERS" field to the tags this would greatly help my cause. Ideally HPX would have a seperate Characters field like e-hentai does, but seeing how it doesn't it feels appropriate to merge the TAGS and CHARACTERS field. 

I've included a sample info.txt to show what it looks like.

[info.txt](https://github.com/happypandax/plugins/files/2377631/info.txt)

**Comment by twiddli** [comment]
Implemented in `0.3.0b`
