### ISSUE TITLE
File Metadata Plugin No longer works in recent versions 

### ISSUE THREAD

**Issue by observeroftime02** [happypandax/plugins#8]
The plugin loads correctly, but upon adding a gallery the following errors are produced

plugin.log: https://pastebin.com/wVLM9gSB
plugin_debug.log: https://pastebin.com/WLf5JjwN

Using Server version 0.5.0 and the latest plugin version.

**Comment by twiddli** [comment]
Should be fixed by HPX `v0.5.1`
